spring:
  r2dbc:
    url: r2dbc:postgresql://postgres-dev:5432/groceries_dev
    username: postgres
    password: 099052
  data:
    redis:
      host: redis-dev
      port: 6379
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres-dev:5432/groceries_dev
    user: postgres
    password: 099052
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

# Security configuration
security:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-for-development-environment-only}
    expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    com.sientong.groceries: DEBUG
    org.flywaydb: DEBUG
    org.springframework.security: ERROR
    org.springframework.security.web.server: ERROR
    org.springframework.actuator: ERROR
    org.springframework.boot.actuate: ERROR
    org.springframework.security.authentication: ERROR
    org.springframework.security.crypto: ERROR

# Development-specific monitoring configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: groceries-delivery-system
      environment: development
    distribution:
      percentiles-histogram:
        http.server.requests: true
    enable:
      jvm: true
      process: true
      system: true
      http: true
