spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/groceries_prod
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/groceries_prod
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.r2dbc: INFO
    com.sientong.groceries: INFO
    org.flywaydb: INFO
    org.springframework.security: INFO
    org.springframework.actuator: INFO
    org.springframework.boot.actuate: INFO

# Production monitoring configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: groceries-delivery-system
      environment: production
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
    enable:
      jvm: true
      process: true
      system: true
      http: true
      logback: true
      disk: true
      executor: true
      cache: true
      db-pool: true
