spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/groceries_db
    username: postgres
    password: 099052
  flyway:
    url: jdbc:postgresql://localhost:5432/groceries_db
    user: postgres
    password: 099052
    locations: classpath:db/migration
    baseline-on-migrate: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  show-actuator: true
  packages-to-scan: com.sientong.groceries.api.controller

jwt:
  secret: your-256-bit-secret-key-here
  expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8080

logging:
  level:
    org.springframework.r2dbc: DEBUG