spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/groceries_db
    username: your_username
    password: your_password
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG